In [1]:
3+4


7

In [2]:
pip install numpy

In [3]:
import numpy as np


In [4]:
mlist=[1,2,7,4,5]

In [5]:
arri=np.array(mlist)
arri

array([1, 2, 7, 4, 5])

In [7]:
arri.shape


(5,)

In [8]:
arr3 = np.array([1, 2, 3, 4], ndmin=5)
print(arr3)

[[[[[1 2 3 4]]]]]


In [9]:
print('number of dimensions :', arr3.ndim)

number of dimensions : 5


In [10]:
arr=np.arange(0,10)

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr.shape


(10,)

In [13]:
print(arr[0:4])

[0 1 2 3]


In [14]:
arr[0:8:2]

array([0, 2, 4, 6])

In [15]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
arr.reshape(2,5).base

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7, 8,9,10,11,12])
arr5.reshape(2, 2, -1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
arr5.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
np.linspace(1,10,15)

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [20]:
arr4 = np.array([1, 2, 3, 4], dtype='i4')
print(arr4)
print(arr4.dtype)

[1 2 3 4]
int32


In [21]:
arr4 = np.array([1, 2, 3, 4], dtype='int')
print(arr4)
print(arr4.dtype)

[1 2 3 4]
int32


In [22]:
newarr = arr4.astype(int)
print(arr4.dtype)

int32


In [23]:
arr4 = np.array([1, 2, 3, 4], dtype='i8')
print(arr4)
print(arr4.dtype)

[1 2 3 4]
int64


In [24]:
newarr = arr.astype(float)

In [25]:
newarr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
x = arr4.view()
arr4[0] = 42
x[1]=5687
print(arr4)
print(x)

[  42 5687    3    4]
[  42 5687    3    4]


In [27]:
x = arr4.copy()
arr4[0] = 65
x[1]=123
print(arr4)
print(x)

[  65 5687    3    4]
[ 42 123   3   4]


In [28]:
for x in arr:
  print(x)

0
1
2
3
4
5
6
7
8
9


In [29]:
for x in arr:
 
    print(x)

0
1
2
3
4
5
6
7
8
9


In [30]:
new=arr.reshape(2,5).copy()
new

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
for x in new:
  for y in x:
    print(y)

0
1
2
3
4
5
6
7
8
9


In [32]:
for x in np.nditer(arr):
  print(x)

0
1
2
3
4
5
6
7
8
9


In [33]:
for x in np.nditer(new[:, ::2]):
  print(x)

0
2
4
5
7
9


In [34]:
for idx, x in np.ndenumerate(new):
  print(idx, x)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9


In [35]:
newarr = np.array_split(arr, 4)

In [36]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
newarr

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]

In [38]:
nwarr = np.array_split(new, 3, axis=1)


In [39]:
nwarr

[array([[0, 1],
        [5, 6]]),
 array([[2, 3],
        [7, 8]]),
 array([[4],
        [9]])]

In [40]:
newarr = np.hsplit(new, 5) #5 no of col
newarr

[array([[0],
        [5]]),
 array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]])]

In [41]:
newarr = np.hstack(new) 
newarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr7 = np.concatenate((arr5, arr4))
arr7

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   65, 5687,    3,    4], dtype=int64)

In [43]:
arr8 = np.concatenate((nwarr[0], nwarr[1]), axis=1)
arr8


array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [44]:
arr9 = np.stack((nwarr[0][0], nwarr[0][1]), axis=1)
arr9

array([[0, 5],
       [1, 6]])

In [45]:
arr10 = np.hstack((nwarr[0][0], nwarr[0][1]))
arr10

array([0, 1, 5, 6])

In [46]:
arr10 = np.vstack((nwarr[0][0], nwarr[0][1]))
arr10

array([[0, 1],
       [5, 6]])

In [47]:
arr10 = np.dstack((nwarr[0][0], nwarr[0][1]))
arr10

array([[[0, 5],
        [1, 6]]])

In [48]:
x = np.where(arr == 1)

print(x)

(array([1], dtype=int64),)


In [49]:
x = np.where(arr%2 == 0)

print(x)

(array([0, 2, 4, 6, 8], dtype=int64),)


In [50]:
x = np.searchsorted(arr, 7) #return index

print(x)


7


In [51]:
x = np.searchsorted(arr, 7, side='right')
print(arr)
print(x)

[0 1 2 3 4 5 6 7 8 9]
8


In [52]:
np.sort(arri)

array([1, 2, 4, 5, 7])

In [53]:
narr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in narr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newar = narr[filter_arr]

filter_arr



[False, False, True, True]

In [54]:
newar

array([43, 44])

In [55]:
filter_arr = narr > 42

newar = narr[filter_arr]

print(filter_arr)
print(newar)

[False False  True  True]
[43 44]


In [56]:
np.random.rand(3,4)


array([[0.56326579, 0.09236787, 0.11083051, 0.97718623],
       [0.94679368, 0.57210678, 0.12021394, 0.70951289],
       [0.62079033, 0.37192438, 0.03164909, 0.69685447]])

In [57]:
np.random.randn(3,4)

array([[ 1.13860344,  1.13046476,  0.05021571, -1.06351733],
       [-1.65567193,  0.22759681,  0.29436975, -0.54042262],
       [ 0.32142601, -0.69127267,  1.17246564, -1.40970692]])

In [58]:
np.random.randint(0,400,12).reshape(3,4)

array([[209, 143, 318,  11],
       [395, 284, 342, 264],
       [315, 356, 208,   4]])

In [59]:
from numpy import random

random.randint(100)


88

In [60]:
random.rand(5,2,4)

array([[[0.00397544, 0.32761281, 0.96291532, 0.15200443],
        [0.02146286, 0.22923537, 0.49512964, 0.24545992]],

       [[0.87629588, 0.34780265, 0.60527807, 0.61572046],
        [0.5141047 , 0.44607897, 0.41855841, 0.16672558]],

       [[0.05424285, 0.19969882, 0.01190827, 0.45964231],
        [0.91332382, 0.47884791, 0.57117986, 0.42045228]],

       [[0.56366549, 0.33364415, 0.5529309 , 0.71385279],
        [0.20040924, 0.90733901, 0.69951206, 0.66804483]],

       [[0.02554825, 0.24911517, 0.59601825, 0.22755436],
        [0.65414319, 0.01314586, 0.67555312, 0.80345587]]])

In [61]:
random.choice([3, 5, 7, 9])

7

In [62]:
random.choice(arr)

1

In [63]:
random.choice([3, 5, 7, 9], size=(3, 5))


array([[9, 5, 9, 5, 5],
       [3, 7, 5, 7, 3],
       [7, 5, 5, 5, 5]])

In [64]:
random.choice(arr, size=(3, 5))


array([[0, 2, 1, 7, 4],
       [6, 1, 8, 2, 8],
       [0, 1, 4, 1, 2]])

In [65]:
random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(10))

array([5, 7, 3, 7, 7, 5, 3, 7, 7, 7])

In [66]:
random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3,4))

array([[7, 7, 7, 7],
       [7, 7, 5, 3],
       [7, 7, 7, 5]])

In [67]:
random.shuffle(arr)  #change orginal array
arr

array([8, 7, 4, 0, 9, 1, 3, 5, 2, 6])

In [68]:
random.permutation(arr) #not change 

array([3, 6, 8, 0, 4, 7, 2, 9, 5, 1])

In [69]:
random.normal(size=(2, 3)) #Generate a random normal distribution of size 2x3

array([[ 0.49817654, -3.85767799, -0.13658583],
       [ 0.27129186, -0.52090057,  1.05839535]])

In [70]:
random.normal(loc=1, scale=2, size=(2, 3))

#Generate a random normal distribution of size 2x3 with mean at 1 and standard deviation of 2

array([[ 3.55497086, -3.19443796, -0.86625763],
       [ 1.54374047,  1.36255377,  0.79925661]])

In [71]:
random.binomial(n=10, p=0.5, size=10)   #n - number of trials. 
#p - probability of occurence of each trial (e.g. for toss of a coin 0.5 each). size - The shape of the returned array.

array([3, 3, 5, 3, 6, 2, 4, 6, 4, 4])

In [72]:
#lam - rate or known number of occurrences e.g. 2 for above problem. size - The shape of the returned array.
random.poisson(lam=2, size=10) 

array([0, 3, 2, 5, 1, 4, 2, 1, 2, 1])

In [73]:
random.uniform(size=(2, 3))

array([[0.02083136, 0.58827672, 0.12745208],
       [0.44086871, 0.69267712, 0.65420756]])

In [74]:
random.uniform(0,6,size=(2, 3)) # lower bound - default 0 .0 ,upper bound - default 1.0.

array([[2.4162968 , 1.52076746, 3.69737331],
       [3.84086089, 3.81964652, 5.97801716]])

In [75]:
random.logistic(loc=1, scale=2, size=(2, 3)) # Draw 2x3 samples from a logistic distribution with mean at 1 and stddev 2.0

array([[ 3.75904641, -0.26876887,  0.72845166],
       [-3.94315182,  5.88698613,  2.39544296]])

In [76]:
random.multinomial(n=6, pvals=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6])

array([2, 1, 1, 0, 2, 0])

In [77]:
random.exponential(scale=2, size=(2, 3))

array([[1.89375922, 1.0359991 , 0.35919317],
       [0.45060367, 0.41493144, 0.84340816]])

In [78]:
random.chisquare(df=2, size=(2, 3))

array([[0.66025403, 2.09232416, 1.05563092],
       [0.97677222, 1.32783272, 0.85758046]])

In [79]:
random.rayleigh(scale=2, size=(2, 3))

array([[1.0712024 , 1.72282854, 1.75567686],
       [2.11781417, 2.0301329 , 3.45073256]])

In [80]:
random.pareto(a=2, size=(2, 3)) # pareto distribution with shape of 2 

array([[10.68677332,  0.26026068,  0.21783017],
       [ 0.03236062,  0.17800844,  0.66247996]])

In [81]:
random.zipf(a=2, size=(2, 3))  # zipf distribution with distribution parameter 2 

array([[1, 1, 1],
       [1, 1, 3]])

In [82]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [83]:
z = np.add(x, y)
z

array([ 5,  7,  9, 11])

In [84]:
def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)
myadd(x,y)


array([5, 7, 9, 11], dtype=object)

In [85]:
z = np.subtract(x, y)
z

array([-3, -3, -3, -3])

In [86]:
z = np.divide(x, y)
z

array([0.25      , 0.4       , 0.5       , 0.57142857])

In [87]:
z = np.power(x, y)
z

array([    1,    32,   729, 16384])

In [88]:
z = np.mod(x, y)
z

array([1, 2, 3, 4])

In [89]:
z = np.remainder(x, y)
z

array([1, 2, 3, 4])

In [90]:
z = np.divmod(x, y)
z

(array([0, 0, 0, 0]), array([1, 2, 3, 4]))

In [91]:
z = np.absolute(x)
z

array([1, 2, 3, 4])

In [92]:
np.sum([x, y])

32

In [93]:
np.sum([x, y] , axis=1)

array([10, 22])

In [94]:
np.cumsum(x)

array([ 1,  3,  6, 10])

In [95]:
np.prod(x)

24

In [96]:
np.prod([x, y])

20160

In [97]:
np.prod([x, y], axis=1)

array([ 24, 840])

In [98]:
np.cumprod(x)

array([ 1,  2,  6, 24])

In [99]:
np.diff(x)

array([1, 1, 1])

In [100]:
np.diff(x , n=2) # n= no of times

array([0, 0])

In [101]:
num1 = 4
num2 = 6

np.lcm(num1, num2)

12

In [102]:
np.lcm.reduce(y)

420

In [103]:
np.gcd(num1, num2)

2

In [104]:
np.gcd.reduce(y)

1

In [105]:
np.sin(np.pi/4)

0.7071067811865476

In [106]:
f = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

np.sin(f)

array([1.        , 0.8660254 , 0.70710678, 0.58778525])

In [107]:
g = np.array([90, 180, 270, 360])

np.deg2rad(g)

array([1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [108]:
h = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

np.rad2deg(h)

array([ 90., 180., 270., 360.])

In [109]:
np.arcsin(1.0)

1.5707963267948966

In [110]:
np.hypot(num1, num2)

7.211102550927978

In [111]:
np.sinh(np.pi/2)

2.3012989023072947

In [112]:
i = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

np.cosh(i)

array([2.50917848, 1.60028686, 1.32460909, 1.20397209])

In [113]:
np.arcsinh(1.0)

0.881373587019543

In [114]:
j = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

np.unique(j)

array([1, 2, 3, 4, 5, 6, 7])

In [115]:
np.union1d(arr, y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
np.intersect1d(arr, y, assume_unique=True)

array([4, 5, 6, 7])

In [117]:
np.setdiff1d(arr, y, assume_unique=True)

array([8, 0, 9, 1, 3, 2])

In [118]:
np.setxor1d(arr, y, assume_unique=True)

array([0, 1, 2, 3, 8, 9])

In [119]:
np.trunc([-3.1666, 3.7667])  # Remove the decimals, and return the float number closest to zero

array([-3.,  3.])

In [120]:
np.fix([-3.1666, 3.6667])

array([-3.,  3.])

In [121]:
np.around(3.1666, 2)

3.17

In [122]:
np.floor([-3.7666, 3.6667]) # The floor() function rounds off decimal to nearest lower integer

array([-4.,  3.])

In [123]:
np.ceil([-3.7666, 3.6667]) # The ceil() function rounds off decimal to nearest upper integer.

array([-3.,  4.])

In [124]:
np.log2(np.arange(1, 10))

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [125]:
from math import log
nplog = np.frompyfunc(log, 2, 1)
print(nplog(100, 10))


2.0
