<a href="https://colab.research.google.com/github/firojahmed1313/MlAITR/blob/main/numpytvr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# **Creating** **Arrays**

In [3]:
arr = np.array([1, 2, 3]) # Converts Python lists or tuples into NumPy arrays.
print(arr)

[1 2 3]


In [4]:
arr1 = np.zeros((2, 3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
arr3 = np.ones((3, 3))
print(arr3)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
arr4 = np.arange(0, 10, 2) # Creates arrays with evenly spaced values (like Python's range).
print(arr4)

[0 2 4 6 8]


In [7]:
arr5 = np.linspace(0, 1, 5) # Creates arrays with evenly spaced numbers between two values (inclusive).
print(arr5)


[0.   0.25 0.5  0.75 1.  ]


In [14]:
arr6 = np.empty((2, 3)) #Creates an array without initializing values (faster than zeros/ones but contains arbitrary values).
print(arr6)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
arr7 = np.full((2, 3), 7) #Creates an array filled with a specified value.
print(arr7)

[[7 7 7]
 [7 7 7]]


In [16]:
arr8 = np.eye(3) #Creates an identity matrix (diagonal of ones).
print(arr8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
arr9 = np.random.rand(2, 3) # Generates arrays with random values from a uniform distribution between 0 and 1.
print(arr9)

[[0.22153134 0.86128031 0.27690964]
 [0.53546054 0.99890971 0.90868658]]


In [19]:
arr10 = np.random.randint(1, 10, (3, 3)) # Generates arrays with random integers from a uniform distribution between low (inclusive) and high (exclusive).
print(arr10)

[[3 9 7]
 [1 2 2]
 [9 2 9]]


# ***Array Attributes***