In [175]:
import numpy as np

# **Creating** **Arrays**

In [176]:
arr = np.array([1, 2, 3]) # Converts Python lists or tuples into NumPy arrays.
print(arr)

[1 2 3]


In [177]:
arr1 = np.zeros((2, 3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [178]:
arr3 = np.ones((3, 3))
print(arr3)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [179]:
arr4 = np.arange(0, 10, 2) # Creates arrays with evenly spaced values (like Python's range).
print(arr4)

[0 2 4 6 8]


In [180]:
arr5 = np.linspace(0, 1, 5) # Creates arrays with evenly spaced numbers between two values (inclusive).
print(arr5)


[0.   0.25 0.5  0.75 1.  ]


In [181]:
arr6 = np.empty((2, 3)) #Creates an array without initializing values (faster than zeros/ones but contains arbitrary values).
print(arr6)

[[0. 0. 0.]
 [0. 0. 0.]]


In [182]:
arr7 = np.full((2, 3), 7) #Creates an array filled with a specified value.
print(arr7)

[[7 7 7]
 [7 7 7]]


In [183]:
arr8 = np.eye(3) #Creates an identity matrix (diagonal of ones).
print(arr8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [184]:
arr9 = np.random.rand(2, 3) # Generates arrays with random values from a uniform distribution between 0 and 1.
print(arr9)

[[0.1074714  0.78544503 0.11249796]
 [0.72422824 0.38565869 0.07337839]]


In [185]:
arr10 = np.random.randint(1, 10, (3, 3)) # Generates arrays with random integers from a uniform distribution between low (inclusive) and high (exclusive).
print(arr10)

[[2 3 6]
 [4 8 1]
 [6 2 6]]


# ***Array Attributes***

In [186]:
print(arr10.shape) # Returns the shape of the array.
print(arr10.dtype) # Returns the data type of the array.
print(arr10.size) # Returns the number of elements in the array.
print(arr10.itemsize) # Returns the size of each element in the array in bytes.
print(arr10.nbytes) # Returns the total size of the array in bytes.
print(arr10.data) # Returns the memory address of the array's data.
print(arr10.ndim) # Returns the number of dimensions of the array.

(3, 3)
int64
9
8
72
2


# **Reshaping and Resizing**

In [187]:
reshaped = arr9.reshape((3, 2)) # Reshapes the array to a new shape without modifying its data.
print(reshaped)
print(arr9)

[[0.1074714  0.78544503]
 [0.11249796 0.72422824]
 [0.38565869 0.07337839]]
[[0.1074714  0.78544503 0.11249796]
 [0.72422824 0.38565869 0.07337839]]


In [188]:
flattened = reshaped.ravel() # Returns a 1D array without copying the data.
print(flattened)

[0.1074714  0.78544503 0.11249796 0.72422824 0.38565869 0.07337839]


In [189]:
flattened = reshaped.flatten() # Creates a flattened copy of the array.
print(flattened)

[0.1074714  0.78544503 0.11249796 0.72422824 0.38565869 0.07337839]


In [190]:
f=arr9.resize((2, 3)) # Resizes the array to a new shape and modifies the original array.
print(arr9)
print(f)

[[0.1074714  0.78544503 0.11249796]
 [0.72422824 0.38565869 0.07337839]]
None


# **Indexing and Slicing**

In [191]:
print(arr)
print(arr[2]) # Returns the element at the specified index.


[1 2 3]
3


In [192]:
print(arr10)
print(arr10[1, 2]) # Returns the element at the specified index.


[[2 3 6]
 [4 8 1]
 [6 2 6]]
1


In [193]:
print(arr10)

print(arr10[1:]) # Returns a view of the array starting from the specified index.


[[2 3 6]
 [4 8 1]
 [6 2 6]]
[[4 8 1]
 [6 2 6]]


In [194]:
print(arr10)
print(arr10[:2]) # Returns a view of the array up to the specified index.



[[2 3 6]
 [4 8 1]
 [6 2 6]]
[[2 3 6]
 [4 8 1]]


In [195]:
print(arr10)
print(arr10[1:3]) # Returns a view of the array from the specified start index to the specified end index.


[[2 3 6]
 [4 8 1]
 [6 2 6]]
[[4 8 1]
 [6 2 6]]


In [196]:
print(arr10)

print(arr10[1:, 1]) # Returns a view of the array along the specified collumn.


[[2 3 6]
 [4 8 1]
 [6 2 6]]
[8 2]


In [197]:
arr11 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr11)
print(arr11[1, :, 0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[5 7]


# ***Operations***

In [198]:
print(arr)
#Arithmetic Operations
print(arr + 10) # Adds 10 to each element of the array.
print(arr - 10) # Subtracts 10 from each element of the array.
print(arr * 2) # Multiplies each element of the array by 2.
print(arr / 2) # Divides each element of the array by 2.

[1 2 3]
[11 12 13]
[-9 -8 -7]
[2 4 6]
[0.5 1.  1.5]


In [199]:
# Aggregate Functions
print(arr)
print(arr.sum()) # Returns the sum of all elements of the array.
print(arr.mean()) # Returns the mean of all elements of the array.
print(arr.std()) # Returns the standard deviation of all elements of the array.
print(arr.var()) # Returns the variance of all elements of the array.
print(arr.max()) # Returns the maximum value of all elements of the array.
print(arr.min()) # Returns the minimum value of all elements of the array.
print(arr.argmax()) # Returns the index of the maximum value of all elements of the array.
print(arr.argmin()) # Returns the index of the minimum value of all elements of the array.


[1 2 3]
6
2.0
0.816496580927726
0.6666666666666666
3
1
2
0


In [200]:
# Sum of elements
total_sum = np.sum(arr10)
print("Sum:", total_sum)

# Product of elements
total_product = np.prod(arr10)
print("Product:", total_product)

# Cumulative sum
cumulative_sum = np.cumsum(arr10)
print("Cumulative Sum:", cumulative_sum)

# Cumulative product
cumulative_product = np.cumprod(arr10)
print("Cumulative Product:", cumulative_product)

Sum: 38
Product: 82944
Cumulative Sum: [ 2  5 11 15 23 24 30 32 38]
Cumulative Product: [    2     6    36   144  1152  1152  6912 13824 82944]


In [201]:
#Logical Operations
print(arr)
print(arr > 2) # Returns a boolean array indicating which elements of the array are greater than 2.
print(arr < 2) # Returns a boolean array indicating which elements of the array are less than 2.
print(arr >= 2) # Returns a boolean array indicating which elements of the array are greater than or equal to 2.
print(arr <= 2) # Returns a boolean array indicating which elements of the array are less than or equal to 2.
print(arr == 2) # Returns a boolean array indicating which elements of the array are equal to 2.
print(arr != 2) # Returns a boolean array indicating which elements of the array are not equal to 2.
print(arr.all()) # Returns a boolean indicating whether all elements of the array are true.
print(arr.any()) # Returns a boolean indicating whether any element of the array is true.
print(np.logical_and(arr > 2, arr < 8))
print(np.logical_or(arr > 2, arr < 8))

[1 2 3]
[False False  True]
[ True False False]
[False  True  True]
[ True  True False]
[False  True False]
[ True False  True]
True
True
[False False  True]
[ True  True  True]


# ***Array Manipulations***

In [202]:
print(arr)
print(arr4)
print(arr5)
result = np.concatenate((arr, arr4, arr5)) # Concatenates three arrays along a specified axis.
print(result)

[1 2 3]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[1.   2.   3.   0.   2.   4.   6.   8.   0.   0.25 0.5  0.75 1.  ]


In [203]:
print(arr)
print(arr9)
print(arr10)
#result = np.concatenate((arr, arr9, arr10)) # Concatenates two arrays along a specified axis.
#error in this line of code because concatenate only works with same dimension.
#print(result)

[1 2 3]
[[0.1074714  0.78544503 0.11249796]
 [0.72422824 0.38565869 0.07337839]]
[[2 3 6]
 [4 8 1]
 [6 2 6]]


In [204]:
print(arr)
print(arr)
print(arr)
result = np.stack((arr, arr, arr)) # Stacks three arrays along a new axis.
#result = np.stack((arr, arr4, arr5)) # same shape error
print(result)

[1 2 3]
[1 2 3]
[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [205]:
np.vstack((arr, arr)) # Stacks arrays vertically (row-wise).



array([[1, 2, 3],
       [1, 2, 3]])

In [206]:
np.hstack((arr, arr)) # Stacks arrays horizontally (column-wise).


array([1, 2, 3, 1, 2, 3])

In [207]:
np.dstack((arr, arr)) # Stacks arrays along the third dimension.

array([[[1, 1],
        [2, 2],
        [3, 3]]])

In [208]:
np.vstack((arr10,arr10))

array([[2, 3, 6],
       [4, 8, 1],
       [6, 2, 6],
       [2, 3, 6],
       [4, 8, 1],
       [6, 2, 6]])

In [209]:
np.hstack((arr10,arr10))

array([[2, 3, 6, 2, 3, 6],
       [4, 8, 1, 4, 8, 1],
       [6, 2, 6, 6, 2, 6]])

In [210]:
np.dstack((arr10,arr10))

array([[[2, 2],
        [3, 3],
        [6, 6]],

       [[4, 4],
        [8, 8],
        [1, 1]],

       [[6, 6],
        [2, 2],
        [6, 6]]])

# ***Splitting***

In [211]:
print(arr)
splitted = np.split(arr, 3) # Split into 3 parts
print(splitted)


[1 2 3]
[array([1]), array([2]), array([3])]


In [212]:
print(arr10)
splitted = np.split(arr10, 3, axis=1) # Split into 3 parts along the second axis
print(splitted)
splitted = np.split(arr10, 3) # Split into 3 parts along the second axis
print(splitted)

[[2 3 6]
 [4 8 1]
 [6 2 6]]
[array([[2],
       [4],
       [6]]), array([[3],
       [8],
       [2]]), array([[6],
       [1],
       [6]])]
[array([[2, 3, 6]]), array([[4, 8, 1]]), array([[6, 2, 6]])]


In [213]:
print(arr10)
splitted = np.vsplit(arr10, 3) # Split into 3 parts along the first axis
print(splitted)

[[2 3 6]
 [4 8 1]
 [6 2 6]]
[array([[2, 3, 6]]), array([[4, 8, 1]]), array([[6, 2, 6]])]


In [214]:
print(arr10)
splitted = np.hsplit(arr10, 3) # Split into 3 parts along the second axis
print(splitted)

[[2 3 6]
 [4 8 1]
 [6 2 6]]
[array([[2],
       [4],
       [6]]), array([[3],
       [8],
       [2]]), array([[6],
       [1],
       [6]])]


In [215]:
print(arr10)
#splitted = np.dsplit(arr10, 3) # Split into 3 parts along the third axis
#print(splitted)


[[2 3 6]
 [4 8 1]
 [6 2 6]]


# ***Flipping Arrays***

In [216]:
print(arr10)
flipped = np.flip(arr10, axis=1) # Flip the array along the specified axis
print(flipped)
flipped = np.fliplr(arr10) # Flips an array left to right.
print(flipped)


[[2 3 6]
 [4 8 1]
 [6 2 6]]
[[6 3 2]
 [1 8 4]
 [6 2 6]]
[[6 3 2]
 [1 8 4]
 [6 2 6]]


In [217]:
print(arr10)

flipped = np.flip(arr10) # Reverses elements along a specified axis.
print(flipped)

[[2 3 6]
 [4 8 1]
 [6 2 6]]
[[6 2 6]
 [1 8 4]
 [6 3 2]]


In [218]:
print(arr10)
flipped = np.flip(arr10, axis=0) # Flip the array along the specified axis
print(flipped)
flipped = np.flipud(arr10) # Flips an array upside down.
print(flipped)

[[2 3 6]
 [4 8 1]
 [6 2 6]]
[[6 2 6]
 [4 8 1]
 [2 3 6]]
[[6 2 6]
 [4 8 1]
 [2 3 6]]


# ***Universal Functions (ufuncs)***

# ***Trigonometric Functions***

In [219]:
angles = np.array([0, np.pi/2, np.pi])
print(angles)

sines = np.sin(angles) # Calculate the sine values of the angles.
print(sines)

cossines = np.cos(angles) # Calculate the cosine values of the angles.
print(cossines)

tansines = np.tan(angles) # Calculate the tangent values of the angles.
print(tansines)

angles2 = np.array([0, 1])
print(angles2)

arcsines = np.arcsin(angles2) # Calculate the arcsine values of the angles.
print(arcsines)

arccossines = np.arccos(angles2) # Calculate the arccosine values of the angles.
print(arccossines)

arctansines = np.arctan(angles2) # Calculate the arctangent values of the angles.
print(arctansines)

degrees = np.degrees(angles) # Convert angles from radians to degrees.
print(degrees)

radians = np.radians(degrees) # Convert angles from degrees to radians.
print(radians)

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[0 1]
[0.         1.57079633]
[1.57079633 0.        ]
[0.         0.78539816]
[  0.  90. 180.]
[0.         1.57079633 3.14159265]


# ***Exponential Functions***

In [220]:
print(arr)
exp_values = np.exp(arr) # Calculates e^x for each element.
print(exp_values)

[1 2 3]
[ 2.71828183  7.3890561  20.08553692]


In [221]:
exp_values = np.expm1(arr) # Calculates e^x - 1 for each element.
print(exp_values)

[ 1.71828183  6.3890561  19.08553692]


In [222]:
exp_values = np.exp2(arr) # Calculates 2^x for each element.
print(exp_values)

[2. 4. 8.]


# ***Logarithmic Functions***

In [223]:
print(arr)
log_values = np.log(arr) # Calculates the natural logarithm for each element.
print(log_values)

log_values = np.log2(arr) # Calculates the base-2 logarithm for each element.
print(log_values)

log_values = np.log10(arr) # Calculates the base-10 logarithm for each element.
print(log_values)

log_values = np.log1p(arr) # Logarithm of 1+x1 + x for precision.
print(log_values)

[1 2 3]
[0.         0.69314718 1.09861229]
[0.        1.        1.5849625]
[0.         0.30103    0.47712125]
[0.69314718 1.09861229 1.38629436]


# ***Useful Mathematical Functions***

In [224]:
matharr = np.array([1.2, -3.4, 5.6])
print(matharr)
absolute = np.abs(matharr) # Returns the absolute value of each element.
print(absolute)
ceiled = np.ceil(matharr) # Returns the smallest integer greater than or equal to each element.
print(ceiled)
floored = np.floor(matharr) # Returns the largest integer less than or equal to each element.
print(floored)
rounded = np.round(matharr) # Returns the element rounded to the nearest integer.
print(rounded)
truncated = np.trunc(matharr) # Returns the truncated value of each element.
print(truncated)
sign = np.sign(matharr) # Returns the sign of each element.
print(sign)
power = np.power(matharr, 2) # Raises each element to the power of 2.
print(power)
sqrt = np.sqrt(arr) # Returns the square root of each element.
print(sqrt)



[ 1.2 -3.4  5.6]
[1.2 3.4 5.6]
[ 2. -3.  6.]
[ 1. -4.  5.]
[ 1. -3.  6.]
[ 1. -3.  5.]
[ 1. -1.  1.]
[ 1.44 11.56 31.36]
[1.         1.41421356 1.73205081]


# ***Masking and Filtering***

# ***Masking***

In [225]:
mask = arr10 > 2
print(mask)

[[False  True  True]
 [ True  True False]
 [ True False  True]]


In [226]:
mask = ((arr10 > 2) & (arr10 < 8))
print(mask)

[[False  True  True]
 [ True False False]
 [ True False  True]]


# ***Filtering***

In [227]:
print(arr)
filtered_arr = arr[arr % 10 == 1]
print(filtered_arr)

[1 2 3]
[1]


In [228]:
print(arr)
filtered_arr = arr[(arr > 1) & (arr < 25)]
print(filtered_arr)
filtered_arr = arr[(arr > 1) | (arr < 25)]
print(filtered_arr)
filtered_arr = arr[(arr > 1) ^ (arr < 25)]
print(filtered_arr)
filtered_arr = arr[~(arr > 1)]
print(filtered_arr)

[1 2 3]
[2 3]
[1 2 3]
[1]
[1]


In [229]:
print(arr10)
mask = arr10 % 2 == 0
filtered_arr = arr10[mask]
print(filtered_arr)

[[2 3 6]
 [4 8 1]
 [6 2 6]]
[2 6 4 8 6 2 6]


In [230]:
print(arr10)
result = np.where(arr10 > 3, -1, arr10) # Replaces elements greater than 3 with -1.
print(result)

[[2 3 6]
 [4 8 1]
 [6 2 6]]
[[ 2  3 -1]
 [-1 -1  1]
 [-1  2 -1]]


# ***Sorting and Searching***

# ***Sorting in numpy***

In [231]:
print(arr10)
sorted_arr = np.sort(arr10)
print(sorted_arr)
sorted_arr = np.sort(arr10, axis=1)
print(sorted_arr)
# arr10.sort()  # orginal array is changed

[[2 3 6]
 [4 8 1]
 [6 2 6]]
[[2 3 6]
 [1 4 8]
 [2 6 6]]
[[2 3 6]
 [1 4 8]
 [2 6 6]]


In [232]:
print(arr10)
sorted_arr = np.sort(arr10, axis=0)
print(sorted_arr)

[[2 3 6]
 [4 8 1]
 [6 2 6]]
[[2 2 1]
 [4 3 6]
 [6 8 6]]


In [233]:
print(arr10)
indices = np.argsort(arr10) # Returns the indices of the sorted elements.
print(indices)



[[2 3 6]
 [4 8 1]
 [6 2 6]]
[[0 1 2]
 [2 0 1]
 [1 0 2]]


In [234]:
sorted_arr2 = arr10[indices] # Sorts the array based on the indices.
print(sorted_arr2)

[[[2 3 6]
  [4 8 1]
  [6 2 6]]

 [[6 2 6]
  [2 3 6]
  [4 8 1]]

 [[4 8 1]
  [2 3 6]
  [6 2 6]]]


# ***Searching***

In [235]:
print(arr10)
unique_elements = np.unique(arr10) # Returns the unique elements of the array.
print(unique_elements)
unique_with_counts = np.unique(arr10, return_counts=True) # Returns the unique elements of the array and their counts.
print(unique_with_counts)
unique_with_indices = np.unique(arr10, return_index=True) # Returns the unique elements of the array and their indices.
print(unique_with_indices)
unique_with_inverse = np.unique(arr10, return_inverse=True) # Returns the unique elements of the array and their inverse indices.
print(unique_with_inverse)


[[2 3 6]
 [4 8 1]
 [6 2 6]]
[1 2 3 4 6 8]
(array([1, 2, 3, 4, 6, 8]), array([1, 2, 1, 1, 3, 1]))
(array([1, 2, 3, 4, 6, 8]), array([5, 0, 1, 3, 2, 4]))
(array([1, 2, 3, 4, 6, 8]), array([1, 2, 4, 3, 5, 0, 4, 1, 4]))


In [236]:
print(arr10)
indices = np.where(arr10 > 2) # Returns the indices of the elements greater than 2.
print(indices)

[[2 3 6]
 [4 8 1]
 [6 2 6]]
(array([0, 0, 1, 1, 2, 2]), array([1, 2, 0, 1, 0, 2]))


# Structured Arrays in NumPy

In [237]:
dtype = [('name', 'U10'), ('age', 'i4'), ('height', 'f4')]

# Create a structured array
data = np.array([('Alice', 25, 5.5), ('Bob', 30, 6.0)], dtype=dtype)
print(data)

print(data['name'])   # ['Alice' 'Bob']
print(data['age'])    # [25 30]

# Accessing individual records
print(data[0])  # ('Alice', 25, 5.5)

data['name'] = ['Charlie' 'Dana', 'Eve']
data['age'] = [2228, 24]
data['height'] = [55.9, 5.6]
print(data)

[('Alice', 25, 5.5) ('Bob', 30, 6. )]
['Alice' 'Bob']
[25 30]
('Alice', 25, 5.5)
[('CharlieDan', 2228, 55.9) ('Eve',   24,  5.6)]


In [238]:
nested_dtype = [('id', 'i4'), ('scores', '3f4')]  # Field 'scores' stores 3 floats
nested_data = np.array([(1, (85.5, 90.0, 88.0)), (2, (75.0, 80.0, 82.5))], dtype=nested_dtype)
print(nested_data)
# [(1, [85.5, 90. , 88. ]) (2, [75. , 80. , 82.5])]

[(1, [85.5, 90. , 88. ]) (2, [75. , 80. , 82.5])]


In [239]:
employee_dtype = [('name', 'U10'), ('age', 'i4'), ('department', 'U10'), ('salary', 'f4')]

# Create structured array
employees = np.array([('Alice', 25, 'HR', 50000.0),
                      ('Bob', 30, 'IT', 60000.0),
                      ('Charlie', 28, 'Finance', 55000.0)], dtype=employee_dtype)

# Filter employees with salary > 55000
high_salary = employees[employees['salary'] > 55000]
print(high_salary)

[('Bob', 30, 'IT', 60000.)]


# ***Linear Algebra with NumPy***

# ***Matrices***

In [240]:
matrix = np.matrix(arr10)
print(matrix)

[[2 3 6]
 [4 8 1]
 [6 2 6]]


In [241]:
print(matrix)
transpose = matrix.T # Transpose the matrix
print(transpose)

[[2 3 6]
 [4 8 1]
 [6 2 6]]
[[2 4 6]
 [3 8 2]
 [6 1 6]]


In [242]:
print(matrix)
inverse = np.linalg.inv(matrix) # Calculate the inverse of the matrix
print(inverse)

[[2 3 6]
 [4 8 1]
 [6 2 6]]
[[-0.22772277  0.02970297  0.22277228]
 [ 0.08910891  0.11881188 -0.10891089]
 [ 0.1980198  -0.06930693 -0.01980198]]


In [243]:
print(matrix)

det = np.linalg.det(matrix) # Calculate the determinant of the matrix
print(det)

[[2 3 6]
 [4 8 1]
 [6 2 6]]
-201.9999999999999


In [244]:
print(matrix)
rank = np.linalg.matrix_rank(matrix) # Calculate the rank of the matrix
print(rank)



[[2 3 6]
 [4 8 1]
 [6 2 6]]
3


In [245]:
print(matrix)
eigenvalues, eigenvectors = np.linalg.eig(matrix) # Calculate the eigenvalues and eigenvectors of the matrix
print(eigenvalues)
print(eigenvectors)

[[2 3 6]
 [4 8 1]
 [6 2 6]]
[-2.66610826 12.70055082  5.96555744]
[[ 0.82092007 -0.51686693  0.25839102]
 [-0.26020412 -0.57479703 -0.78487232]
 [-0.50831492 -0.63439495  0.56321357]]


In [246]:
print(matrix)
trace = np.trace(matrix)
print(trace)


[[2 3 6]
 [4 8 1]
 [6 2 6]]
16


# ***Solving Linear Equations***

In [247]:
# 2x + y = 5
# x + 3y = 7

A = np.array([[2, 1], [1, 3]])
b = np.array([5, 7])

# Solve for x
x = np.linalg.solve(A, b)
print("Solution:", x)

Solution: [1.6 1.8]


Using the Inverse Matrix

In [248]:
# x=A^(−1)⋅bx

A_inv = np.linalg.inv(A)
x = np.dot(A_inv, b) # Compute x using A_inv
print("Solution using inverse:", x)

Solution using inverse: [1.6 1.8]


Using Matrix Multiplication

In [249]:
x = np.dot(np.linalg.inv(A), b)  # Equivalent to A_inv @ b
print("Solution using matrix multiplication:", x)

Solution using matrix multiplication: [1.6 1.8]


Verifying the Solution

In [250]:
is_correct = np.allclose(np.dot(A, x), b)
print("Solution verified:", is_correct)

Solution verified: True


Handling Special Cases when determinant is 0, meaning it does not have an inverse

In [251]:
singular_matrix = np.array([[1, 2], [2, 4]])  # Determinant = 0
try:
    x = np.linalg.solve(singular_matrix, b)
except np.linalg.LinAlgError as e:
    print("Error:", e)

Error: Singular matrix


# ***Singular Value Decomposition (SVD)***

# ***NumPy for Statistical and Mathematical Operations***

# ***Descriptive Statistics***

In [252]:
print(arr10)
mean = np.mean(arr10)
median = np.median(arr10)
variance = np.var(arr10)
std_deviation = np.std(arr10)

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)

[[2 3 6]
 [4 8 1]
 [6 2 6]]
Mean: 4.222222222222222
Median: 4.0
Variance: 5.061728395061729
Standard Deviation: 2.249828525701843


In [253]:
print(arr10)

mean_rows = np.mean(arr10, axis=1)

# Mean along columns
mean_columns = np.mean(arr10, axis=0)

print("Mean (rows):", mean_rows)
print("Mean (columns):", mean_columns)

median_rows = np.median(arr10, axis=1)

# median along columns
median_columns = np.median(arr10, axis=0)

print("median (rows):", median_rows)
print("median (columns):", median_columns)

[[2 3 6]
 [4 8 1]
 [6 2 6]]
Mean (rows): [3.66666667 4.33333333 4.66666667]
Mean (columns): [4.         4.33333333 4.33333333]
median (rows): [3. 4. 6.]
median (columns): [4. 3. 6.]


# ***Random Number Generation***

In [254]:
# Set seed for reproducibility
np.random.seed(42)

# Random float array (uniform distribution)
random_floats = np.random.rand(3, 3)
print("Random Floats:\n", random_floats)

# Random integers between 10 and 50
random_integers = np.random.randint(10, 50, size=(2, 3))
print("Random Integers:\n", random_integers)

# Random samples from a normal distribution
random_normals = np.random.randn(5)
print("Random Normals:\n", random_normals)

# Random choice from a list
choices = np.random.choice([1, 2, 3, 4, 5], size=4, replace=False)
print("Random Choices:\n", choices)
# Random choice from a list
choices = np.random.choice([1, 2, 3, 4, 5], size=7, replace=True)
print("Random Choices:\n", choices)

Random Floats:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
Random Integers:
 [[33 12 31]
 [11 33 39]]
Random Normals:
 [-0.58087813 -0.52516981 -0.57138017 -0.92408284 -2.61254901]
Random Choices:
 [2 5 4 3]
Random Choices:
 [2 4 4 3 4 4 1]


**Monte Carlo Simulations**

In [255]:
# Monte Carlo Simulation: Estimate Pi
n_points = 10000
x = np.random.rand(n_points)
y = np.random.rand(n_points)
inside_circle = np.sum(x**2 + y**2 <= 1)

# Estimate of Pi
pi_estimate = (inside_circle / n_points) * 4
print("Estimated Pi:", pi_estimate)


Estimated Pi: 3.1568
